### ISSUE TITLE
demo_ui.py: Backward 10 frames

### ISSUE THREAD

**Issue by PFython** [qmasingarbe/pymiere#16]
I'm going to just post the error messages for the next few issues - they all relate to demo_up.py on the same environment as follows:

Windows 10 latest version, Premiere Pro (CC) latest version, Python 3.9.

Please let me know if you don't want this level of detail as there may well be a common root cause e.g. incompatible versions or known bug in Premiere Pro 14.5.0... otherwise I'll keep posting and hope that's not too demoralising!

<class 'pymiere.core.ExtendScriptError'> 
Error at line 2 : Illegal Parameter type
 1      try{
 2      var tmp = $._pymiere['D6zv6ieWY0'].setPlayerPosition(11552436000000);       
 3      if(typeof tmp === 'object' && tmp !== null){ <traceback object at 0x000001CC28323780>
Traceback (most recent call last):
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\demo_ui.py", line 151, in backward_func
    self.active_sequence.setPlayerPosition(current_time.ticks)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\objects\premiere_objects.py", line 1095, in setPlayerPosition
    self._eval_on_this_object("setPlayerPosition({})".format(_format_object_to_es(pos)))
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\core.py", line 163, in _eval_on_this_object
    result = _eval_script_returning_object(line)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\core.py", line 425, in _eval_script_returning_object
    result = eval_script(script, decode_json=True)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\core.py", line 102, in eval_script
    raise ExtendScriptError(response_decoded)
pymiere.core.ExtendScriptError:
Error at line 2 : Illegal Parameter type
 1      try{
 2      var tmp = $._pymiere['D6zv6ieWY0'].setPlayerPosition(11552436000000);       
 3      if(typeof tmp === 'object' && tmp !== null){

**Comment by qmasingarbe** [comment]
Pymiere was not tested thoroughly on PremierePro 2020, thanks for reporting those problems.
This one has been fixed by https://github.com/qmasingarbe/pymiere/commit/de11e6731ab40bce19aee7f615c4455bcf75c520
