### ISSUE TITLE
demo_ui.py: Forward 10 frames

### ISSUE THREAD

**Issue by PFython** [qmasingarbe/pymiere#17]
<class 'pymiere.core.ExtendScriptError'>
Error at line 2 : Illegal Parameter type
 1      try{
 2      var tmp = $._pymiere['nHrZr6M6kW'].setPlayerPosition(11755648800000);
 3      if(typeof tmp === 'object' && tmp !== null){ <traceback object at 0x0000025ED8A43C40>
Traceback (most recent call last):
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\demo_ui.py", line 22, in wrapper
    result = func(self, *args, **kwargs)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\demo_ui.py", line 145, in forward_func
    self.active_sequence.setPlayerPosition(current_time.ticks)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\objects\premiere_objects.py", line 1095, in setPlayerPosition
    self._eval_on_this_object("setPlayerPosition({})".format(_format_object_to_es(pos)))
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\core.py", line 163, in _eval_on_this_object
    result = _eval_script_returning_object(line)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\core.py", line 425, in _eval_script_returning_object
    result = eval_script(script, decode_json=True)
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\pymiere\core.py", line 102, in eval_script
    raise ExtendScriptError(response_decoded)
pymiere.core.ExtendScriptError:
Error at line 2 : Illegal Parameter type
 1      try{
 2      var tmp = $._pymiere['nHrZr6M6kW'].setPlayerPosition(11755648800000);       
 3      if(typeof tmp === 'object' && tmp !== null){

**Comment by qmasingarbe** [comment]
Fixed by https://github.com/qmasingarbe/pymiere/commit/de11e6731ab40bce19aee7f615c4455bcf75c520
