### ISSUE TITLE
Following Motion Graphics Example For Adding Text Results in Error

### ISSUE THREAD

**Issue by shaibruhis** [qmasingarbe/pymiere#43]
Following the [Motion Graphics Example for adding text](https://github.com/qmasingarbe/pymiere/blob/master/example_and_documentation.md#motion-graphics-templates) I get the following error: 
```
>>> mgt_clip.getMGTComponent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pymiere/objects/premiere_objects.py", line 5773, in getMGTComponent
    return Component(**self._eval_on_this_object("getMGTComponent()"))
TypeError: type object argument after ** must be a mapping, not NoneType
```

**Comment by shaibruhis** [comment]
The problem ([also described here](https://community.adobe.com/t5/premiere-pro-discussions/complete-object-model-explanation-of-extendscript-for-premiere-pro/m-p/11291333)) is the .mogrt file I was importing was a ppro .mogrt file and not an ae .mogurt file. I wasn't aware this would cause a problem and am not sure how to tell the difference (other than dir/file naming)

**Comment by qmasingarbe** [comment]
Hi @shaibruhis ,
I fixed the crash for `mgt_clip.getMGTComponent()`. It should now properly return None to match the behavior of the Premiere API (ccfa2d74c678f066bae154752a0b62c9e9296536).
I seems indeed that there are two types of Motion Graphics templates, you can difference them in the editing interface where some are simple an assembly of Premiere Pro effects and other are more complicated options exposed from After Effects.
![see screenshot](https://user-images.githubusercontent.com/29820110/137951127-edb5928c-2660-4f21-8423-5b4b832d12a9.png)
The first type will return None for the `getMGTComponent` because you can directly access the effects parameters via the `Clip.components` attribute. Note that both of them will return True to `Clip.isMGT()`
I will update my documentation to explain this!
