### ISSUE TITLE
After the script is executed, an error occurs. What should i do to resolve this issue?

### ISSUE THREAD

**Issue by dragonkyl** [qmasingarbe/pymiere#78]
Exception ignored in: <function PymiereBaseObject.__del__ at 0x00000160B0C08220>
Traceback (most recent call last):
  File "D:\D\Python\Python311\Lib\site-packages\pymiere\core.py", line 178, in __del__
  File "D:\D\Python\Python311\Lib\site-packages\pymiere\core.py", line 77, in eval_script
  File "D:\D\Python\Python311\Lib\site-packages\pymiere\core.py", line 39, in check_premiere_is_alive
  File "D:\D\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
  File "D:\D\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
  File "D:\D\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
  File "D:\D\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
  File "D:\D\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
  File "D:\D\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
  File "D:\D\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
  File "D:\D\Python\Python311\Lib\site-packages\urllib3\connection.py", line 463, in getresponse
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function PymiereBaseObject.__del__ at 0x00000160B0C08220>
Traceback (most recent call last):
  File "D:\D\Python\Python311\Lib\site-packages\pymiere\core.py", line 178, in __del__
  File "D:\D\Python\Python311\Lib\site-packages\pymiere\core.py", line 77, in eval_script
  File "D:\D\Python\Python311\Lib\site-packages\pymiere\core.py", line 39, in check_premiere_is_alive
  File "D:\D\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
  File "D:\D\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
  File "D:\D\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
  File "D:\D\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
  File "D:\D\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
  File "D:\D\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
  File "D:\D\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
  File "D:\D\Python\Python311\Lib\site-packages\urllib3\connection.py", line 463, in getresponse
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by AndreAnjosTD** [comment]
Hi @dragonkyl, we are facing the same issue. using python 37 and 39 at the moment.
Our current situation is that we are using a later version of Premiere (2024), that is likely not supported and that might be what the import issue is about.
What version of Premier are you currently on?
thanks!

**Comment by hedley-david** [comment]
Hello, I have a Pymiere working in Python 3.6 with Premiere 2024.1
I also have a Python 3.10 install that works with Pymiere but I stay on the lower version of Python b/c of my workplace studio.

**Comment by AndreAnjosTD** [comment]
Hi @hedley-david, thanks for that! That's interesting that it's working correctly for you with 2024. I will try and test it with 3.6 and 3.10.

**Comment by dragonkyl** [comment]
hi.@AndreAnjosTD   with Premiere 2024.

**Comment by hedley-david** [comment]
> Hi @hedley-david, thanks for that! That's interesting that it's working correctly for you with 2024. I will try and test it with 3.6 and 3.10.

You're welcome. Screencap to confirm functionality in 3.6 on both Mac and PC.
I also recommend having one version of PPro dedicated to Pymiere. I have automated a lot of batch sequence making for VOD distribution, and the syntax of what PPro would accept changed from 2021 / 2022 / 2023 each time.

![image](https://github.com/qmasingarbe/pymiere/assets/102440609/b87f32aa-3879-4380-b6e1-33943da62958)
